"""Every lockfile in the repo pins the same commons, at the commit pyproject's tag resolves to.

This exists because the repo had two regeneration paths and a lockfile fell between them.
`scripts/lock.py` recompiled `requirements-dev.lock` and `requirements-gcp.lock`; `make lock`
had raw `uv pip compile` lines for all four. Whoever bumped the commons ran the script, so
`requirements-demo.lock` kept pinning superseded builds of agent-eval-kit and hex-service-kit
while `pyproject.toml` declared newer ones.

That is not a cosmetic drift. The commons `pyproject.toml` declared is where
`EvalReport.passed` stops returning True for an EMPTY result set, and where the promotion-gate
client refuses a service response carrying no attested evidence. The CI job that builds the
headless browser evidence installs the demo lock ON TOP of the dev lock, so it actively
downgraded the eval kit the dev lock had just installed correctly, with no diff anywhere to
notice, because the other lockfiles were right.

So the assertions below are deliberately about the SET of lockfiles, discovered by glob rather
than listed: a new `requirements-<something>.lock` is covered the moment it is added, which is
exactly the property the hardcoded list did not have. They are cheap file reads, no network.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]

#: Every lockfile the repo ships, discovered rather than enumerated. See the module docstring.
LOCKFILES: tuple[str, ...] = tuple(sorted(p.name for p in REPO_ROOT.glob("requirements-*.lock")))

#: `<name> @ git+<url>@<ref>` as a lockfile body writes it.
_LOCK_PIN = re.compile(r"^([a-z0-9-]+) @ git\+(\S+?)@(\S+)\s*$", re.M)

#: `"<name>[extras] @ git+<url>@<tag>",` as pyproject declares it.
_DECLARED_PIN = re.compile(
    r"([a-z0-9-]+)(?:\[[^\]]*\])?\s*@\s*git\+\S+?@(v[0-9][^\s\"']*)",
)

#: The `#   <package>  v<tag> = <commit>` map the lockfile header carries.
_TAG_COMMIT_LINE = re.compile(
    r"^#\s+(?P<package>[a-z0-9-]+)\s+(?P<tag>v[0-9][^\s]*)\s*=\s*(?P<commit>[0-9a-f]{40})\s*$"
)


def locked_pins(text: str) -> dict[str, str]:
    """Package -> the git ref a lockfile BODY pins it at (comment lines cannot match)."""
    return {name: ref for name, _url, ref in _LOCK_PIN.findall(text)}


def _read(name: str) -> str:
    return (REPO_ROOT / name).read_text(encoding="utf-8")


def _declared_tags() -> dict[str, str]:
    return dict(_DECLARED_PIN.findall((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")))


def _tag_commit_map(text: str) -> dict[str, tuple[str, str]]:
    return {
        m["package"]: (m["tag"], m["commit"])
        for m in (_TAG_COMMIT_LINE.match(raw) for raw in text.splitlines())
        if m
    }


def test_the_repo_actually_ships_the_lockfiles_this_module_thinks_it_does() -> None:
    """A glob that matches nothing would make every test below pass by vacuum."""
    assert set(LOCKFILES) >= {
        "requirements-build.lock",
        "requirements-dev.lock",
        "requirements-gcp.lock",
        "requirements-demo.lock",
    }, f"discovered only {LOCKFILES}; the glob is not finding the lockfiles CI installs"


def _make_lock_recipe() -> str:
    """The body of the Makefile's `lock` target, which is what `make lock` actually runs."""
    text = (REPO_ROOT / "Makefile").read_text(encoding="utf-8")
    match = re.search(r"^lock:.*?\n((?:\t.*\n)+)", text, re.M | re.S)
    assert match, "the Makefile has no `lock` target, so nothing regenerates the lockfiles"
    return match.group(1)


def test_make_lock_regenerates_every_lockfile_the_repo_ships() -> None:
    """The root cause, asserted directly: a lockfile outside `make lock` is one that drifts.

    Two regeneration paths is one too many. `requirements-build.lock` compiles from
    `requirements-build.in` and pins no commons, so it stays a direct uv line in the recipe;
    everything derived from `pyproject.toml` goes through `scripts/lock.py`, which is the only
    thing that puts the destroyed `tag = commit` header back. Either way a lockfile has to be
    named somewhere `make lock` reaches, or it is regenerated by hand or not at all.
    """
    script = (REPO_ROOT / "scripts" / "lock.py").read_text(encoding="utf-8")
    reachable = _make_lock_recipe() + script
    uncovered = [name for name in LOCKFILES if name not in reachable]
    assert not uncovered, (
        f"{', '.join(uncovered)} is shipped but `make lock` does not regenerate it, so it will "
        "drift the moment a dependency is bumped"
    )


def test_the_pyproject_lockfiles_go_through_the_script_not_a_raw_uv_line() -> None:
    """A raw `uv pip compile` line in the recipe destroys the header the pin map lives in.

    That is exactly how the two paths diverged: the recipe recompiled four files with raw uv,
    the script recompiled two of them properly, and the demo lock ended up regenerated by
    whichever one somebody happened to run.
    """
    recipe = _make_lock_recipe()
    assert "scripts/lock.py" in recipe, "`make lock` has to run the script, not open-code uv"
    script = (REPO_ROOT / "scripts" / "lock.py").read_text(encoding="utf-8")
    for name in LOCKFILES:
        if name == "requirements-build.lock":  # compiled from the .in file, pins no commons
            continue
        assert f'"{name}"' in script, (
            f"{name} is derived from pyproject.toml but is not a scripts/lock.py target"
        )
        assert f"-o {name}" not in recipe, (
            f"{name} is recompiled by a raw uv line in the Makefile, which strips its header"
        )


@pytest.mark.parametrize("name", LOCKFILES)
def test_each_lockfile_pins_the_commons_by_commit_not_by_tag(name: str) -> None:
    """A tag is a movable pointer; pinning one is not a lock."""
    for package, ref in sorted(locked_pins(_read(name)).items()):
        assert re.fullmatch(r"[0-9a-f]{40}", ref), (
            f"{name} pins {package} at {ref!r}, which is not a 40-character commit sha"
        )


def test_every_lockfile_pins_each_commons_at_the_same_commit() -> None:
    """The defect this module was written for: one lockfile a release behind the others.

    Nothing else in the gate compares them, so a job installing the odd one out silently ran a
    superseded commons. Disagreement is always a bug: the lockfiles are compiled from one
    `pyproject.toml`, so the only way two can differ is that one was not recompiled.
    """
    by_file = {name: locked_pins(_read(name)) for name in LOCKFILES}
    packages = sorted({package for pins in by_file.values() for package in pins})
    assert packages, "no lockfile pins any commons; the pin regex is not matching"
    for package in packages:
        pinned = {name: pins[package] for name, pins in by_file.items() if package in pins}
        assert len(set(pinned.values())) == 1, (
            f"{package} is pinned at more than one commit across the lockfiles: "
            + ", ".join(f"{name} -> {ref}" for name, ref in sorted(pinned.items()))
        )


@pytest.mark.parametrize("name", LOCKFILES)
def test_each_locked_commit_is_recorded_against_the_tag_pyproject_names(name: str) -> None:
    """The offline proof that the pinned commit IS the tag pyproject declares.

    pyproject names a tag, because a diff of two shas tells a reviewer nothing. The lockfile
    pins the commit. The header ties the two together, and this asserts the three-way agreement
    without a network call.
    """
    text = _read(name)
    locked = locked_pins(text)
    declared = _declared_tags()
    recorded = _tag_commit_map(text)
    assert declared, "pyproject.toml declares no git-pinned commons"
    assert set(recorded) == set(locked), (
        f"{name}: the header tag map covers {sorted(recorded)} but the body pins {sorted(locked)}"
    )
    for package, (tag, commit) in sorted(recorded.items()):
        assert package in declared, f"{name} pins {package}, which pyproject.toml does not declare"
        assert commit == locked[package], (
            f"{name}: header records {package} at {commit}, the body pins {locked[package]}"
        )
        assert tag == declared[package], (
            f"{name}: header records {package} {tag}, pyproject.toml declares {declared[package]}"
        )


def test_the_comparison_can_actually_see_a_downgraded_pin() -> None:
    """Prove the parser is not the reason the checks above are green.

    A file-comparison test passes just as happily when its regex matches nothing, so this feeds
    it the exact shape of the defect (one lockfile a release behind) and asserts it is visible.
    """
    current = _read("requirements-dev.lock")
    pins = locked_pins(current)
    assert "agent-eval-kit" in pins, "the dev lock should pin agent-eval-kit"
    downgraded = current.replace(pins["agent-eval-kit"], "4" * 40)
    assert locked_pins(downgraded)["agent-eval-kit"] == "4" * 40, (
        "the parser cannot see a changed commit, so agreement between the files proves nothing"
    )
    assert locked_pins("# agent-eval-kit @ git+https://example.invalid/x@" + "5" * 40) == {}, (
        "a commented-out line is not a pin, and counting one would make the map wrong"
    )
